// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/rbac.proto

package rbac

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetUserMenuReqReq) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	return nil
}
func (this *GetUserMenuReqRsp) Validate() error {
	return nil
}
func (this *CreateRuleReq) Validate() error {
	for _, item := range this.Data {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Data", err)
			}
		}
	}
	return nil
}
func (this *RuleInfo) Validate() error {
	if !(len(this.UrlPath) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("UrlPath", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.UrlPath))
	}
	if !(len(this.Title) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Title))
	}
	if !(this.Type > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be greater than '0'`, this.Type))
	}
	return nil
}
func (this *UpdateRuleReq) Validate() error {
	if !(len(this.UrlPath) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("UrlPath", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.UrlPath))
	}
	return nil
}
func (this *SelectRuleReq) Validate() error {
	return nil
}
func (this *SelectRuleRsp) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *CreateAuthGroupReq) Validate() error {
	if !(len(this.Title) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.Title))
	}
	if len(this.RuleIds) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("RuleIds", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.RuleIds))
	}
	return nil
}
func (this *UpdateAuthGroupReq) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	return nil
}
func (this *SelectAuthGroupReq) Validate() error {
	return nil
}
func (this *SelectAuthGroupRsp) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *AuthGroupRuleInfo) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	for _, item := range this.RuleList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RuleList", err)
			}
		}
	}
	return nil
}
func (this *UpdateAuthGroupAccessReq) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	if len(this.GroupIds) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("GroupIds", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.GroupIds))
	}
	return nil
}
func (this *VerifyUserAuthReq) Validate() error {
	if !(this.Uid > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Uid", fmt.Errorf(`value '%v' must be greater than '0'`, this.Uid))
	}
	if !(len(this.UrlPath) > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("UrlPath", fmt.Errorf(`value '%v' must have a length greater than '0'`, this.UrlPath))
	}
	return nil
}
func (this *VerifyUserAuthRsp) Validate() error {
	return nil
}
func (this *EmptyRsp) Validate() error {
	return nil
}
